# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
name: Upload to Maven Central Sonatype
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: secring
  displayName: 'Download secring'
  inputs:
    secureFile: 'secring.gpg'

- task: DownloadSecureFile@1
  name: gradleprops
  displayName: 'Download gradle.properties'
  inputs:
    secureFile: 'gradle.properties'

#      echo Putting the secring file into the gpg directory
#      sudo cp ~/.gpg $(caCertificate.secureFilePath)
- script: |
    echo Getting some info
    pwd
    ls ~/
    echo $(secring.secureFilePath)
    mkdir .gradle
    cp $(gradleprops.secureFilePath) .gradle/


- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    options: "-Psigning.secretKeyRingFile=$(secring.secureFilePath)"
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'uploadSonatype'
