# Azure Pipeline that publishes to maven central on every master merge.
name: Upload to Maven Central Sonatype
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: secring
  displayName: 'Download secring'
  inputs:
    secureFile: 'secring.gpg'

- task: DownloadSecureFile@1
  name: gradleprops
  displayName: 'Download gradle.properties'
  inputs:
    secureFile: 'gradle.properties'

- script: |
    echo Setting up secure things...
    echo Making .gradle directory...
    mkdir ~/.gradle
    echo Done!
    echo Moving gradle.properties into it...
    cp $(gradleprops.secureFilePath) ~/.gradle/
    echo Done!


- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    options: "-Psigning.secretKeyRingFile=$(secring.secureFilePath)"
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'uploadSonatype'
